### ISSUE TITLE
数据缺失

### ISSUE THREAD

**Issue by Howardcl** [zhoudaoying/openpose_with_object-detection#1]
博主您好，您能提供video_test.py中缺少的数据文件（data_pose.npy）吗？

**Comment by Howardcl** [comment]
sorry ,I find data in other folder.

**Comment by zhoudaoying** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhoudaoying/openpose_with_object-detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月12日(星期六) 中午1:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhoudaoying/openpose_with_object-detection] 数据缺失 (Issue #1)





 
博主您好，您能提供video_test.py中缺少的数据文件（data_pose.npy）吗？
